### ISSUE TITLE
Loading/Spinner Component

### ISSUE THREAD

**Issue by archik408** [grodno-vr/grodno-vr.github.io#3]
Создать компонент Loading/Spinner, что-то вроде того, что на прикрепленном скриншоте.
Компонент должен появляться во время загрузки локации/места (т.к. сфеерическое фото долго загружается)

![screen shot 2018-01-15 at 12 25 34 pm](https://user-images.githubusercontent.com/10139861/34935666-acf7b564-f9ef-11e7-924a-6d48f98e9ea5.png)

Пример спиннера можно посмотреть тут:
http://vr.britishmuseum.org/

**Comment by zarendar** [comment]
I take it

**Comment by archik408** [comment]
Я создал 2 компонента: WebLoading и VRLoading. В данный момент показывается только первый, нужно подключить второй, для режима VR. К тексту Loading... нужно добавить spinner

**Comment by archik408** [comment]
https://github.com/grodno-vr/grodno-vr.github.io/commit/fc6b9fb685891b64d73815223ab5ca8c14ed0288
