### ISSUE TITLE
Stereoscopy/stereo imaging

### ISSUE THREAD

**Issue by archik408** [grodno-vr/grodno-vr.github.io#7]
Нужно разобраться почему не работает кнопка "режим стерео"

![screen shot 2018-01-15 at 12 37 00 pm](https://user-images.githubusercontent.com/10139861/34935998-d6456bd6-f9f0-11e7-97af-138d640e370c.png)

И как включить такой режим в браузерах и на девайсах

**Comment by Xerotico** [comment]
Как включить WebVR? https://webvr.info/developers/
Было бы круто использовать полифил, чтобы не трогать никакие флаги и поддерживать большее число браузеров. https://github.com/googlevr/webvr-polyfill

**Comment by Xerotico** [comment]
Добавил полифил, теперь работает во всех браузерах
![screenshot from 2018-01-18 17-16-23](https://user-images.githubusercontent.com/4882086/35102243-5b059cea-fc73-11e7-800c-a3f59118e808.png)

PR: https://github.com/grodno-vr/grodno-vr.github.io/pull/8
